title: Shared Infrastructures for Tangible Tabletops and Interactive Surfaces
description: Workshop at ITS 2015, Nov. 15, Madeira, Portugal

url: http://mmbuw.github.io/workshop
baseurl: "/workshop"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
