title: Shared Infrastructures for Tangible Tabletops and Interactive Surfaces
description: Workshop at ITS 2015, Nov. 15, Madeira, Portugal

url: http://mmbuw.github.io/workshop
baseurl: "/workshop"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Program
   url: /program
 - title: Organizers
   url: /organizers

social:
   github: floe
   twitter: floemuc
   email: floe@butterbrot.org
